import { Component, OnInit } from '@angular/core';
import { ClassApiService } from '../../services/class/class-api.service';
import { StudentApiService } from '../../services/student/student-api.service';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-new-class',
  templateUrl: './new-class.component.html',
  styleUrls: ['./new-class.component.css']
})
export class NewClassComponent implements OnInit {

  newClassData: Object;
  newClassForm: FormGroup;
  is_submitted: boolean = false;
  api_post_successful:boolean;
  api_post_fail_message: string = "";
  form_is_valid: boolean =false;

  constructor(private formBuilder: FormBuilder, private router: Router, public classService: ClassApiService) { }

  ngOnInit() {
    //Create a new Class object mapping it to the API Class object's fields 
    // Also, used by this.newClassData Object: name, desc, link, students
    this.newClassForm = this.formBuilder.group({
      name: ['', Validators.required],
      desc: ['', Validators.required],
      // omitting 'link' field since it is generated by the backend
      // omitting 'students' since it is not required initially
    })
  }

  onSubmit(){
    this.is_submitted = true;

    if (this.newClassForm.invalid){
      return;
    }

    this.newClassData = {
      name: this.newClassForm.controls.name.value,
      desc: this.newClassForm.controls.desc.value,
      link: '',
      students: []
    }

    this.createNewClass();
  }

  createNewClass(){
    this.classService.addNewClass(this.newClassData)
    .subscribe(
      data => {
        this.api_post_successful = true;
        this.form_is_valid = true;
        this.router.navigate(['/classes']);
      },
      err => {
        this.api_post_successful = false;
        this.api_post_fail_message ="Sorry, this new class could be created. Please, try again later.";
      },
      () => { }
    )
    
  }

}
