# Generated by Django 2.1.7 on 2019-02-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_student_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='link',
            field=models.SlugField(blank=True, max_length=115, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='link',
            field=models.SlugField(blank=True, max_length=115, unique=True),
        ),
    ]
